# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: offenes-parlament

email: info@okfn.de

# this means to ignore newlines until "baseurl:"
description: ''

# the subpath of your site, e.g. /blog
baseurl: ''

# the base hostname & protocol for your site
url: ''

twitter_username: okfde
github_username:  okfde

# scripts to load on all pages
scripts: []

# Build settings
markdown: kramdown
